name: Build and Push to branch for GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
      - name: Fetch repo
        uses: actions/checkout@main
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.3.0
        
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
        
      - name: Deploy to GitHub Pages
        run: git subtree -split --prefix dist -b release
        
      - name: Force push to branch for GitHub Pages
        run: git push -f origin release:ReleaseToGithubPages
        
      - name: Delete release branch
        run: git branch -D release
      

