name: build-to-github-pages-branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:                
      - name: Fetch repo - main branch
        uses: actions/checkout@v2
        with:
          ref: main
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.3.0
        
      - name: Install dependencies
        run: npm install
      
      - name: Build Vue Application
        run: npm run build
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set config
        run: |
          git config user.name "Ansgar Lichter"
          git config user.email "lichteransgar@gmail.com"
        
      - name: Include dist folder
        run: |
          git add -f dist
          git commit --allow-empty-message --no-verify
       
      - name: Split dist folder
        run: git subtree split --prefix dist -b build
        
      - name: Push dist folder to GitHub Pages
        run: |
          git push --force origin build:releaseToGithubPages
          git branch -D build
      

