name: build-to-github-pages-branch

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:                
      - name: Fetch repo - main branch
        uses: actions/checkout@v4
        with:
          ref: main
        
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
        
      - name: Install dependencies
        run: npm install
      
      - name: Build Vue Application
        run: npm run build
        
      - name: Upload build for deployment
        uses: actions/upload-artifact@v4
        with:
          name: built-repo
          path: dist
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:                  
      - name: Fetch repo - release branch
        uses: actions/checkout@v4
        with:
          ref: releaseToGithubPages
      
      - name: Create new empty branch
        run: git switch --orphan build
        
      - name: Load built repository
        uses: actions/download-artifact@v4
        with:
          name: built-repo
          
      - name: Set config
        run: |
          git config user.name "Ansgar Lichter"
          git config user.email "lichteransgar@gmail.com"
        
      - name: Commit build
        run: |
          git add --force --all
          git commit --allow-empty-message -m ''
        
      - name: Push build to release branch
        run: |
          git push origin --force build:releaseToGithubPages
      

